kubes:
  hosts:
    utmp:
      ansible_host: 192.168.86.78
      ansible_connection: ssh
      ansible_ssh_user: "deploy"
      # ansible_ssh_pass: "{{ ssh_pass }}"
      ansible_become_pass: "{{become_pass}}"
    pitmp:
      ansible_host: 192.168.86.80
      ansible_connection: ssh
      ansible_ssh_user: "deploy"
      # ansible_ssh_pass: "{{ ssh_pass }}"
      ansible_become_pass: "{{become_pass}}"